in:
  type: randomj
  rows: 16
  threads: 1
  primary_key: myid
  schema:
    - {name: myid,     type: long}
    - {name: named,    type: string}
    - {name: x_flag,   type: boolean}
    - {name: pit_rate, type: double}
    - {name: score,    type: long}
    - {name: time,     type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y/%m/%d'}

out:
  type: aster
  url: jdbc:ncluster://192.168.100.100
  user: beehive
  password: beehive
  database: beehive
  table: t1
  distribute_key: myid
  mode: replace
  after_load: "ANALYZE public.t1"